### ISSUE TITLE
plz fix when fluentd.logs.autoscaling.enabled: true error

### ISSUE THREAD

**Issue by txjjjjj** [SumoLogic/sumologic-kubernetes-collection#3220] opened 2023-08-18 12:10 UTC
when `fluentd.logs.autoscaling.enabled: true`

and then 
```
 helm template sumologic-agent ./sumologic  --namespace=sumologic -f values.yaml > manifest.yaml


Error: YAML parse error on sumologic/templates/logs/fluentd/hpa.yaml: error converting YAML to JSON: yaml: line 19: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML

```

helm chart version: 3.12.1

**Comment by swiatekm-sumo** [comment] 2023-08-18 12:23
This is a duplicate of #3151, it's already fixed in main, and the fix will be released in version 3.13 next week.

**Closed** 2023-08-30 16:24 UTC
Labels: bug
