### ISSUE TITLE
Need override to pass ImagePullSecrets in Sumo OTEL events templates

### ISSUE THREAD

**Issue by rupeshnemade** [SumoLogic/sumologic-kubernetes-collection#2678] opened 2022-12-09 13:13 UTC
**Is your feature request related to a problem? Please describe.**
We want to pull images from local artifactory by passing imagepullsecrets so that pod can authenticate with artifactory & pull images.

**Describe the solution you'd like**
I would prefer having filed for imagepullsecret in https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/events/otelcol/statefulset.yaml

https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/deploy/helm/sumologic/templates/setup/job.yaml#L54

**Comment by nehajaju** [comment] 2022-12-13 11:06
Raised PR for the same : https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/2689

**Comment by swiatekm-sumo** [comment] 2022-12-15 12:00
Are you sure this doesn't work as-is by setting `sumologic.pullSecrets`? It looks like the events StatefulSet has the right ServiceAccount set. Same for the setup Job, `sumologic.setup.job.pullSecrets` should work already.

**Comment by swiatekm-sumo** [comment] 2022-12-21 09:55
Closing this, as it appears to work as intended.

**Closed by swiatekm-sumo** 2022-12-21 09:55 UTC
Labels: enhancement
