### ISSUE TITLE
Sumologic k8s collection issues too many queries

### ISSUE THREAD

**Issue by roy-work** [SumoLogic/sumologic-kubernetes-collection#1248] opened 2020-12-15 22:54 UTC
**Describe the bug**

We run the sumologic kubernetes collection on top of Azure AKS. We have been having significant trouble with k8s API server queries across the board, basically from anything that issues them, including components of the Sumologic Kubernetes Collection.

For example, in one of our clusters, the user `system:serviceaccount:NS:sumologic` with the UA of `rest-client/2.1.0 (linux-gnu x86_64) ruby/2.6.5p114` has made 101k API calls over 24h, or ~1qps. This seems higher that necessary.

Looking at the individual calls that get made, for example, I see things like:

```
12/15/2020, 4:03:34 PM get /api/v1/namespaces/ns-a/pods/nginx-ingress-controller-577d76cf8f-46nnx
12/15/2020, 4:03:34 PM get /api/v1/namespaces/ns-a
12/15/2020, 4:03:36 PM get /api/v1/namespaces/ns-b/pods/REDACT-v2-67d5ddd77d-7m6zf
12/15/2020, 4:03:36 PM get /api/v1/namespaces/ns-b
12/15/2020, 4:03:41 PM get /api/v1/namespaces/ns-b/pods/REDACT-76b99bfb88-vcmqq
12/15/2020, 4:03:41 PM get /api/v1/namespaces/ns-b
12/15/2020, 4:03:43 PM get /api/v1/namespaces/ns-b/pods/REDACT-b7fc9bbd4-qr56t
12/15/2020, 4:03:43 PM get /api/v1/namespaces/ns-b
12/15/2020, 4:05:43 PM get /api/v1/namespaces/ns-b/pods/REDACT-7756b8d8fb-c7zrv
12/15/2020, 4:05:43 PM get /api/v1/namespaces/ns-b
```

* is it necessary to repeatedly query the NS?
* It seems like something is simply trying to list pods, in which case a _single_ `list` call to `/namespaces/:ns/pods` would be more efficient, no?

**Logs**

In addition to the above access logs, here's an example crash, when the API server fails to respond:

<details><summary>Example crash log</summary>

```
#Thread:0x00007f5fefc4bae8@/usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:269 run terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `sysread': error reading from socket: Connection reset by peer (HTTP::ConnectionError)
from /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/timeout/null.rb:45:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/connection.rb:212:in `read_more'
from /usr/local/bundle/gems/http-4.4.1/lib/http/connection.rb:92:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/response/body.rb:30:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/response/body.rb:36:in `each'
from /usr/local/bundle/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:269:in `block in configure'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `sysread': Connection reset by peer (Errno::ECONNRESET)
from /usr/local/lib/ruby/2.6.0/openssl/buffering.rb:125:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/timeout/null.rb:45:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/connection.rb:212:in `read_more'
from /usr/local/bundle/gems/http-4.4.1/lib/http/connection.rb:92:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/response/body.rb:30:in `readpartial'
from /usr/local/bundle/gems/http-4.4.1/lib/http/response/body.rb:36:in `each'
from /usr/local/bundle/gems/kubeclient-4.5.0/lib/kubeclient/watch_stream.rb:25:in `each'
from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:36:in `start_namespace_watch'
from /usr/local/bundle/gems/fluent-plugin-kubernetes_metadata_filter-2.4.1/lib/fluent/plugin/filter_kubernetes_metadata.rb:269:in `block in configure'
Unexpected error error reading from socket: Connection reset by peer
```
</details>

Logs which can be helpful in investigating the issue.

**Command used to install/upgrade Collection**
Direct command which you used to install/upgrade collection.

We use Helm to template the charts, & flux to install the result. There's not a direct command I can list here. 

**Configuration**
Configuration used for Collection e.g. values.yaml for helm.
(This is a huge configuration; can it be narrowed to something specific?)

**To Reproduce**
Steps to reproduce the behavior.

Deploy Sumologic to AKS, particularly in a busy cluster, as the API load from Sumologic seems to scale w/ the workload on the cluster.

**Expected behavior**

I expect API server calls not to fail, for one; we're trying to resolve that with AKS separately, and it was that investigation that led to Sumologic's API use.

**Environment (please complete the following information):**
 - **Collection version** (e.g. `helm ls -n sumologic`): 1.1.0-beta.2
 - **Kubernetes version** (e.g. `kubectl version`): 1.16.9
 - **Cloud provider**: Azure AKS
 - **Others**:

**Anything else do we need to know**
Add any other context about the problem here, e.g. issue happens only occasionally.

**Comment by astencel-sumo** [comment] 2020-12-16 15:51
Hi @roy-work,

Thanks for reporting this. We are aware of the fact that Fluentd performs a lot of API requests. This is a problem particularly in AKS, where we've seen SNAT port exhaustion because of this (https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/891). We are currently working on improving this situation.

As for the crash from `kubernetes_metadata_filter` plugin you've pasted, this is a bit different. This is caused by https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/249 and we have a fix for this coming in 1.3.4 which you should be able to see quite soon.

**Comment by astencel-sumo** [comment] 2020-12-18 17:11
Release v1.3.4 is out of the door so please check it to see if it helps with that `kubernetes_metadata_filter` issue.

I will have a look at the repeated namespace requests next week. We should not be doing this, I believe we have an internal cache for that, but I'll have another look to be sure.

**Comment by pmalek-sumo** [comment] 2021-06-07 16:28
Hi @roy-work

1.3.x is almost deprecated (going to be next month) and most of the development is now directed towards 2.X (2.2 as of today).

I'm closing this issue as of now. If you feel that there's still something to address don't hesitate to comment.

**Closed by pmalek-sumo** 2021-06-07 16:28 UTC
Labels: bug
